ALTER TABLE placas ADD COLUMN IF NOT EXISTS nome_exibicao VARCHAR(120);
ALTER TABLE placas ADD COLUMN IF NOT EXISTS tipo_dispositivo VARCHAR(30);
ALTER TABLE placas ADD COLUMN IF NOT EXISTS local_uso VARCHAR(120);
ALTER TABLE placas ADD COLUMN IF NOT EXISTS loja_unidade VARCHAR(120);
ALTER TABLE placas ADD COLUMN IF NOT EXISTS responsavel VARCHAR(120);
ALTER TABLE placas ADD COLUMN IF NOT EXISTS observacao VARCHAR(500);
